# Example ingestion job definition used by `smiles ingest`.
job:
  output_dir: data/raw
  checkpoint_dir: data/checkpoints
  batch_size: 500
  concurrency: 2
  compress_output: true
  sources:
    - type: pubchem
      name: pubchem
      options:
        index_file: data/Index_of_pubchem_Compound_CURRENT-Full_SDF.html
        download_dir: data/raw/pubchem
        identifier_tag: PUBCHEM_COMPOUND_CID
        smiles_tag: PUBCHEM_OPENEYE_ISO_SMILES
        metadata_tags:
          - PUBCHEM_IUPAC_INCHI
    - type: zinc
      name: zinc
      options:
        wget_file: data/ZINC22-downloader-2D-smi.gz.wget
        download_dir: data/raw/zinc22
        download_missing: true
    - type: chembl
      name: chembl
      options:
        link_file: data/chEMBL_sdf_link.txt
        download_dir: data/raw/chembl
