# Example ingestion job definition used by `smiles ingest`.
job:
  output_dir: data/raw
  checkpoint_dir: data/checkpoints
  batch_size: 500
  concurrency: 2
  compress_output: true
  sources:
    - type: zinc
      name: zinc
      options:
        uri_file: data/ZINC-downloader-2D-txt.uri
        download_dir: data/raw/zinc22
        download_missing: true
