# Example ingestion job definition used by `smiles ingest`.
job:
  output_dir: data/raw
  checkpoint_dir: data/checkpoints
  batch_size: 500
  concurrency: 2
  compress_output: true
  sources:
    - type: pubchem
      name: pubchem
      options:
        ftp_host: ftp.ncbi.nlm.nih.gov
        ftp_directory: pubchem/Compound/CURRENT-Full/SDF
        identifier_tag: PUBCHEM_COMPOUND_CID
        smiles_tag: PUBCHEM_OPENEYE_ISO_SMILES
    - type: zinc
      name: zinc
      options:
        base_url: https://example.test/zinc
        endpoint: substances
        records_path: [records]
        next_cursor_path: [next]
        id_field: zinc_id
        smiles_field: smiles
